# build-and-test-linux.yml

# Copyright (c) Mateusz Jandura. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build and test (Linux)
on:
  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - '**/**.md'
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [Clang, GCC]
        arch: [x64, x86]
        config: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Install Ninja
        run: |
          sudo apt-get install ninja-build

      - name: Set up Clang
        if: ${{ matrix.compiler == 'Clang' }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}

      - name: Set up GCC
        if: ${{ matrix.compiler == 'GCC' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: ${{ matrix.arch }}

      - name: Configure project (x64 Clang)
        if: ${{ matrix.compiler == 'Clang' && matrix.arch == 'x64' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_FLAGS="-target x86_64-pc-linux-gnu" -DCMAKE_CXX_FLAGS="-target x86_64-pc-linux-gnu"
          -DMJXSDK_BUILD_BENCHMARKS=ON -DMJXSDK_BUILD_TESTS=ON -DMJXSDK_INSTALL_LIBRARY=ON

      - name: Configure project (x86 Clang)
        if: ${{ matrix.compiler == 'Clang' && matrix.arch == 'x86' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_FLAGS="-target i686-pc-linux-gnu" -DCMAKE_CXX_FLAGS="-target i686-pc-linux-gnu"
          -DMJXSDK_BUILD_BENCHMARKS=ON -DMJXSDK_BUILD_TESTS=ON -DMJXSDK_INSTALL_LIBRARY=ON

      - name: Configure project (x64 GCC)
        if: ${{ matrix.compiler == 'GCC' && matrix.arch == 'x64' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_FLAGS="-m64" -DCMAKE_CXX_FLAGS="-m64" -DMJXSDK_BUILD_BENCHMARKS=ON
          -DMJXSDK_BUILD_TESTS=ON -DMJXSDK_INSTALL_LIBRARY=ON

      - name: Configure project (x86 GCC)
        if: ${{ matrix.compiler == 'GCC' && matrix.arch == 'x86' }}
        run: >
          cmake --preset=${{ matrix.arch }} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -DMJXSDK_BUILD_BENCHMARKS=ON
          -DMJXSDK_BUILD_TESTS=ON -DMJXSDK_INSTALL_LIBRARY=ON

      - name: Build project
        run: |
          cmake --build build/${{ matrix.arch }} --preset=${{ matrix.arch }} --config ${{ matrix.config }}

      - name: Install project
        run: |
          cmake --install build/${{ matrix.arch }} --config ${{ matrix.config }}

      - name: Run tests
        run: |
          ctest --test-dir build/${{ matrix.arch }}/tests --output-on-failure -C ${{ matrix.config }}